In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9))
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [4]:
a = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(a.ndim)

3


In [5]:
print(np.__version__)

1.20.2


In [11]:
b = np.ones([3,3], dtype=int)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
b = np.array([[1,2,3],[2,4,5]])
b[0,1]

2

In [22]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])
c.shape

(2, 3, 3)